spring.application.name=folhapagamento

spring.datasource.url=jdbc:mysql://localhost:3306/folhapagamento
spring.datasource.username=folhapagamento
spring.datasource.password=folhapagamento
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
